import "dotenv/config";import express from "express";import cors from "cors";import helmet from "helmet";import{z}from"zod";
const c={port:Number(process.env.PORT??8787),key:process.env.OPENROUTER_API_KEY??"",model:process.env.OPENROUTER_MODEL??"openai/gpt-6-astra",fallback:(process.env.OPENROUTER_FALLBACK_MODELS??"").split(",").map(x=>x.trim()).filter(Boolean),origin:process.env.FRONTEND_ORIGIN??"http://localhost:5173"};
const system="You are Silica Ai, a coding-first AI engineering assistant. Help design, implement, debug, optimize, test and ship software. Inspect supplied code before proposing changes. Preserve APIs and conventions unless asked otherwise. Never invent files, APIs, errors, test results or tool output. For performance work consider allocations, algorithms, I/O, contention, cache behavior and concurrency. For security use validation, least privilege, safe defaults and server-side secrets. Give concise reasoning summaries, not hidden chain-of-thought. Prefer complete runnable code and verification steps.";
const app=express();app.disable("x-powered-by");app.use(helmet({crossOriginResourcePolicy:false}));app.use(cors({origin:c.origin.split(",").map(x=>x.trim()),methods:["GET","POST","OPTIONS"],allowedHeaders:["Content-Type"]}));app.use(express.json({limit:1500000}));
const buckets=new Map<string,{n:number;t:number}>();function allow(ip:string){const now=Date.now(),b=buckets.get(ip);if(!b||now>=b.t){buckets.set(ip,{n:1,t:now+60000});return true}if(b.n>=30)return false;b.n++;return true}
const schema=z.object({messages:z.array(z.object({role:z.enum(["user","assistant"]),content:z.string().min(1).max(120000)})).min(1).max(80),files:z.array(z.object({path:z.string().min(1).max(500),language:z.string().max(80).optional(),content:z.string().max(120000)})).max(20).optional(),model:z.string().regex(/^[a-zA-Z0-9._:/-]{2,160}$/).optional()});
app.get("/health",(_,r)=>r.json({ok:true,service:"silica-ai-api",model:c.model}));
app.post("/v1/chat",async(req,res)=>{if(!allow(req.ip||"unknown")){res.status(429).json({error:"Rate limit exceeded."});return}const p=schema.safeParse(req.body);if(!p.success){res.status(400).json({error:"Invalid request.",details:p.error.flatten()});return}if(!c.key){res.status(503).json({error:"OPENROUTER_API_KEY is not configured."});return}
const{messages,files=[],model}=p.data;const ctx=files.map(f=>"\n--- FILE "+f.path+" ("+(f.language??"text")+") ---\n"+f.content+"\n--- END FILE ---").join("");const models=[model??c.model,...c.fallback].filter((x,i,a)=>x&&a.indexOf(x)===i);let up:Response|undefined,chosen="",last="OpenRouter request failed.";
for(const m of models){const r=await fetch("https://openrouter.ai/api/v1/chat/completions",{method:"POST",headers:{Authorization:"Bearer "+c.key,"Content-Type":"application/json","HTTP-Referer":c.origin,"X-Title":"Silica Ai"},body:JSON.stringify({model:m,messages:[{role:"system",content:system+"\nUser repository context:"+ctx},...messages],stream:true,temperature:.15}),signal:AbortSignal.timeout(120000)});if(r.ok&&r.body){up=r;chosen=m;break}last=m+": "+r.status+" "+(await r.text()).slice(0,400)}
if(!up){res.status(502).json({error:last});return}res.status(200).set({"Content-Type":"text/event-stream; charset=utf-8","Cache-Control":"no-cache, no-transform","Connection":"keep-alive","X-Silica-Model":chosen}).flushHeaders();
const reader=up.body!.getReader(),dec=new TextDecoder();let buf="";const emit=(x:unknown)=>res.write("data: "+JSON.stringify(x)+"\n\n");
try{while(true){const x=await reader.read();if(x.done)break;buf+=dec.decode(x.value,{stream:true});const ev=buf.split("\n\n");buf=ev.pop()??"";for(const e of ev)for(const line of e.split("\n")){if(!line.startsWith("data: "))continue;const d=line.slice(6).trim();if(d==="[DONE]")continue;try{const j=JSON.parse(d),t=j?.choices?.[0]?.delta?.content;if(typeof t==="string"&&t)emit({type:"delta",text:t})}catch{}}}emit({type:"done",model:chosen});res.end()}catch(e){emit({type:"error",error:e instanceof Error?e.message:"Stream failed."});res.end()}});
app.use((_,r)=>r.status(404).json({error:"Not found."}));app.listen(c.port,()=>console.log("Silica Ai API listening on "+c.port));